### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by Shafaq-S** [cvg/glue-factory#113]
I am training LightGlue on my own dataset (which consists of RGB images only) by running this experiment:
python -m gluefactory.train sp+lg_homography --conf gluefactory/configs/superpoint-open+lightglue_homography.yaml
However, when I run inference after training, I get no matches at all. Any leads to solve this problem?
Also, is it possible to visualize matches during training after each epoch?

**Comment by hzy01-code** [comment]
Have you solved this problem?

**Comment by Shafaq-S** [comment]
Not yet. Are you facing the same problem?

**Comment by ne24kit** [comment]
Hi everyone,
I encountered the same issue and found a way to solve it.

You can create your own dataset class by using [`[homographies.py](https://github.com/cvg/glue-factory/blob/main/gluefactory/datasets/homographies.py)`](https://github.com/cvg/glue-factory/blob/main/gluefactory/datasets/homographies.py) as a reference.

Here's what you need to do:

1. **Override the `_init` method** in your custom dataset class. You can remove the download logic since you're using your own local data.

2. **Place your images** in the `./gluefactory/data/<your_dataset_folder>` directory.

3. **Create a `config.yaml` file** for your dataset with the following structure:

```yaml
data:
  name:       <your_dataset_name>
  data_dir:   <your_dataset_folder>  # relative to ./gluefactory/data
  image_dir:  ''                     # optional subdirectory
  image_list: null
  train_size: 450
  val_size:   50
  batch_size: 12
  num_workers: 4
  shuffle_seed: 42
  # add other parameters as needed
```
