### ISSUE TITLE
Possibly faster training

### ISSUE THREAD

**Issue by ducha-aiki** [cvg/glue-factory#39]
I have been experimenting with faster training and it seems that OneCycle policy with `max_lr=3e-4` provides the same results (based on training and val metrics) than standard, but 2x faster.
Maybe that could help others, who would be training on other types of features.
<img width="900" alt="image" src="https://github.com/cvg/glue-factory/assets/4803565/aaa08183-3b7e-4b5a-8f0b-0a6caac6e32f">
<img width="891" alt="image" src="https://github.com/cvg/glue-factory/assets/4803565/77b86488-4f46-4414-9752-345b5b1d4ce7">

```
    lr_schedule:
        max_lr: 3e-4
        epochs: 20
        steps_per_epoch: 782
        type: OneCycleLR
```
